local H = ...

for _, channelOnly in ipairs({ false, true }) do
	H.test("catch before stop preserves the previous miss " .. tostring(channelOnly), function()
		local w, FK, stats = H.stats()
		w:cast()
		w:stop()
		w:advance(1)
		w:cast(channelOnly)
		w:catch(false)
		H.eq(stats:GetSessionStats().casts, 2)
		H.eq(stats:GetSessionStats().gotAway, 1)
		w:stop()
		w:event("LOOT_CLOSED")
		H.eq(FK.State.isFishing, false, "the new catch closes its own cast")
		w:cast()
		w:advance(1)
		H.eq(stats:GetSessionStats().casts, 2)
		H.eq(stats:GetSessionStats().catches, 1)
		H.eq(FK.chardb.stats.totalGotAway, 1)
	end)
end

H.test("rapid recasts keep both catches", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:catch(false)
	w:cast()
	w:event("LOOT_CLOSED")
	H.eq(FK.State.isFishing, true, "new cast stays active")
	w:stop()
	w:catch(true)
	w:advance(1)
	H.eq(stats:GetSessionStats().catches, 2, "catches")
	H.eq(stats:GetSessionStats().casts, 2, "casts")
	H.eq(stats:GetSessionStats().gotAway, 0, "misses")
	H.eq(#FK.chardb.lootHistory, 2, "loot history")
	H.eq(FK.chardb.stats.fishCaught[6291].count, 4, "fish quantity")
end)

H.test("old loot close preserves the next cast timeout", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:catch(false)
	w:cast()
	w:stop()
	w:event("LOOT_CLOSED")
	H.eq(FK.State.waitingForLoot, true)
	w:advance(1)
	H.eq(stats:GetSessionStats().casts, 2)
	H.eq(stats:GetSessionStats().gotAway, 1)
end)

H.test("empty ready followed by populated loot counts once", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:event("LOOT_READY")
	w:catch(true)
	H.eq(stats:GetSessionStats().catches, 1)
	H.eq(#FK.chardb.lootHistory, 1)
end)

H.test("no loot timeout records a missed fish", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:advance(1)
	H.eq(stats:GetSessionStats().casts, 1, "casts")
	H.eq(stats:GetSessionStats().gotAway, 1, "missed fish")
	H.eq(FK.chardb.stats.totalGotAway, 1, "saved misses")
	H.eq(FK.db.globalStats.totalCasts, 1)
	w:event("PLAYER_LOGOUT")
	H.eq(FK.chardb.sessions[1].gotAway, 1, "saved session misses")
end)

H.test("duplicate interruptions and stops count one miss", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:event("UNIT_SPELLCAST_INTERRUPTED", "player", "Cast-1", 7620)
	w:event("UNIT_SPELLCAST_FAILED", "player", "Cast-1", 7620)
	w:advance(0)
	w:stop()
	w:advance(2)
	H.eq(stats:GetSessionStats().casts, 1)
	H.eq(stats:GetSessionStats().gotAway, 1)
	H.eq(FK.chardb.stats.totalGotAway, 1)
end)

H.test("cancelled cast animation is not a missed fish", function()
	local w, _, stats = H.stats()
	w:event("UNIT_SPELLCAST_START", "player", "Cast-1", 7620)
	w:event("UNIT_SPELLCAST_INTERRUPTED", "player", "Cast-1", 7620)
	w:advance(0)
	H.eq(stats:GetSessionStats().casts, 0)
	H.eq(stats:GetSessionStats().gotAway, 0)
end)

H.test("recast invalidates pending interruption and timeout", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:event("UNIT_SPELLCAST_INTERRUPTED", "player", "Cast-1", 7620)
	w:cast()
	w:advance(1)
	H.eq(FK.State.isFishing, true)
	H.eq(stats:GetSessionStats().casts, 0)
	H.eq(stats:GetSessionStats().gotAway, 0)
	w:stop()
	w:catch(true)
	H.eq(stats:GetSessionStats().casts, 1)
end)

H.test("late loot corrects a timeout without adding a cast", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:stop()
	w:advance(1)
	w:catch(true)
	H.eq(stats:GetSessionStats().casts, 1)
	H.eq(stats:GetSessionStats().catches, 1)
	H.eq(stats:GetSessionStats().gotAway, 0)
	H.eq(FK.chardb.stats.totalGotAway, 0)
	H.eq(FK.db.globalStats.totalCasts, 1)
	H.eq(FK.chardb.stats.zoneStats["Test Lake"].casts, 1)
end)

H.test("channel only recasts use separate outcomes", function()
	local w, _, stats = H.stats()
	w:cast(true)
	w:stop()
	w:catch(false)
	w:cast(true)
	w:event("LOOT_CLOSED")
	w:stop()
	w:catch(true)
	H.eq(stats:GetSessionStats().casts, 2)
	H.eq(stats:GetSessionStats().catches, 2)
end)

H.test("loot before channel stop prevents a false timeout", function()
	local w, FK, stats = H.stats()
	w:cast()
	w:catch(false)
	w:stop()
	w:advance(1)
	H.eq(FK.State.isFishing, true)
	H.eq(stats:GetSessionStats().gotAway, 0)
	w:event("LOOT_CLOSED")
	H.eq(FK.State.isFishing, false)
	H.eq(stats:GetSessionStats().casts, 1)
end)

H.test("unrelated loot cannot finish fishing", function()
	local w, FK, stats = H.stats()
	w:cast()
	w.fishingLoot = false
	w:catch(true)
	H.eq(stats:GetSessionStats().catches, 0)
	H.eq(FK.State.isFishing, true)
end)

H.test("disabled tracking records no misses", function()
	local w, FK, stats = H.stats()
	FK.db.settings.trackStats = false
	w:cast()
	w:stop()
	w:advance(1)
	H.eq(stats:GetSessionStats().casts, 0)
	H.eq(stats:GetSessionStats().gotAway, 0)
	H.eq(FK.chardb.stats.totalGotAway, 0)
end)
